### PR TITLE
Fixed issue #13  and #11 by adding Cordova support

### PR DESCRIPTION
**Pull request by aziflaj**

### CODE REVIEW

**Comment by dashohoxha** [comment]
@aziflaj This is a simple app that does not need native libraries. As far as I know Cordova supports native libraries (on Android and iOS). Are you sure that it is needed? Have you tested it in FirefoxOS simulator and Android simulator?

**Comment by dashohoxha** [comment]
I mean, from the workshops that I have followed (the last one in Prishtina, at SFK14) all you need for a FirefoxOS app is a manifest file, and everything else can be just normal HTML+CSS+JS.

**Comment by aziflaj** [comment]
@dashohoxha I am using Cordova as a simple way of porting the web app in a small native app. It is needed if you think of porting it in Android. 

As for Firefox OS, Cordova does the thing for you. All you have to do is execute
`cordova prepare firefoxos` in the base dir and its OK, it adds the manifest file automatically.

On Android, I tried on my phone (no emulator) and it was OK. As for Firefox OS, can't test it right now, but I don't think that will rise any errors or problems

**Comment by dashohoxha** [comment]
Aldo, first of all thanks for trying to help.
However, when it comes to code quality, I am worse than Linus Torvalds :) (I am praising myself)

Look at this tutorial: http://www.sitepoint.com/firefox-os-application-primer/
In this app we have no need for SMS, vibration, camera, etc., so there is no need for Cordova. Let's keep it simple. Just a manifest file and everything will be OK. This is also what I remember from the workshop with Janis in Prishtina.
Then you have to package it and upload to the FirefoxOS market place.

I am not sure about Android, but maybe it is the same thing, just a manifest file and everything is OK.

We have another project for trying to build a native app (for Android and iOS):
 - https://github.com/B-Translator/vocabulary-ionic
If you want I can give you full access on this project. Then we should find out how to upload an app on the Android market.

**Comment by dashohoxha** [comment]
Fixed by 944b3ad23f6b6a2026ed5f1b61752b52aebe7c64 .

**Pull request closed without merging**
